version: 2

references:

  ## Docker image configurations

  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

  ## Workspace

  workspace: &workspace
    ~/workspace

jobs:

  ## Build debug APK and instrumented test APK

  build:
    <<: *android_config

workflows:
  version: 2
  workflow:
    jobs:
      - build