version: 2

references:

  ## Cache

  cache_key: &cache_key
    key: cache-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle
        - ~/.m2

  ## Workspace

  workspace: &workspace
    ~/workspace
  persist_debug_workspace: &persist_debug_workspace
    persist_to_workspace:
      root: *workspace
      paths:
        - mobile/build/intermediates
        - mobile/build/outputs/androidTest-results
        - mobile/build/outputs/apk
        - mobile/build/outputs/code-coverage
        - mobile/build/test-results

  ## Docker image configurations

  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

  ## Keys

  # Google Services

  export_gservices_key: &export_gservices_key
    run:
      name: Export Google Services key environment variable
      command: echo 'export GOOGLE_SERVICES_KEY="$GOOGLE_SERVICES_KEY"' >> $BASH_ENV
  decode_gservices_key: &decode_gservices_key
    run:
      name: Decode Google Services key
      command: mkdir -p mobile && echo $GOOGLE_SERVICES_KEY | base64 -di > mobile/google-services.json

jobs:

  ## Build debug APK and instrumented test APK

  build:
    <<: *android_config
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Download dependencies
          command: chmod +x gradlew && ./gradlew androidDependencies
      - *save_cache
      - *export_gservices_key
      - *decode_gservices_key
      - run:
          name: Gradle build (debug)
          command: ./gradlew -PciBuild=true assembleDebug assembleAndroidTest
      - run:
          name: Add workspace directories
          command: mkdir -p ~/workspace/mobile/build/intermediates && mkdir -p ~/workspace/mobile/build/outputs/androidTest-results && mkdir -p ~/workspace/mobile/build/outputs/apk && mkdir -p ~/workspace/mobile/build/outputs/code-coverage && mkdir -p ~/workspace/mobile/build/test-results
      - *persist_debug_workspace
      - store_artifacts:
          path: mobile/build/outputs/apk/
          destination: /apk/

workflows:
  version: 2
  workflow:
    jobs:
      - build